(cl:in-package dofbot_info-srv)
(cl:export '(TAR_X-VAL
          TAR_X
          TAR_Y-VAL
          TAR_Y
          TAR_Z-VAL
          TAR_Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          CUR_JOINT1-VAL
          CUR_JOINT1
          CUR_JOINT2-VAL
          CUR_JOINT2
          CUR_JOINT3-VAL
          CUR_JOINT3
          CUR_JOINT4-VAL
          CUR_JOINT4
          CUR_JOINT5-VAL
          CUR_JOINT5
          CUR_JOINT6-VAL
          CUR_JOINT6
          KIN_NAME-VAL
          KIN_NAME
          JOINT1-VAL
          JOINT1
          JOINT2-VAL
          JOINT2
          JOINT3-VAL
          JOINT3
          JOINT4-VAL
          JOINT4
          JOINT5-VAL
          JOINT5
          JOINT6-VAL
          JOINT6
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
))